[package]
name = "chip8_core"
version = "0.1.0"
edition = "2021"

[lints.rust]
dead_code = "allow"

[features]
default = ["std"]
std = []


[dependencies]
log = "0.4.22"
anyhow = "1.0.93"
rand = "0.8.5"

[dev-dependencies]
pretty_assertions = "1.4.1"
