[package]
name = "chip8_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
emulator = { path = "../chip8_core" }
clap = { version = "4.5.26", features = ["derive"] }
anyhow = "1.0.95"
env_logger = "0.11.6"
ratatui = "0.29.0"
crossterm = "0.28.1"