[package]
name = "chip8_sdl"
version = "0.1.0"
edition = "2021"

[dependencies]
emulator = { path = "../chip8_core" }
env_logger = "0.11.6"
clap = { version = "4.5.26", features = ["derive"] }
anyhow = "1.0.95"
sdl2 = { version = "0.37.0", features = ["unsafe_textures"] }
log = "0.4.22"
